name: data
version: 0.12.0

homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.

environment:
  sdk: ^3.0.0
dependencies:
  collection: ^1.18.0
  meta: ^1.9.0
  more: ^4.0.1
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0