name: data
version: 0.15.0

homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.
topics:
  - math
  - numeric
  - stats
  - tensor

environment:
  sdk: ^3.8.0
dependencies:
  collection: ^1.19.0
  meta: ^1.17.0
  more: ^4.6.0
dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
