name: data
version: 0.15.2

homepage: https://github.com/renggli/dart-data
description: A time and space efficient collection of data structures and
  algorithms to deal with data in Dart.
topics:
  - math
  - numeric
  - stats
  - tensor

environment:
  sdk: ^3.13.0
dependencies:
  collection: ^1.19.1
  meta: ^1.19.0
  more: ^4.7.0
dev_dependencies:
  build_runner: ^2.16.0
  build_web_compilers: ^4.8.9
  lints: ^6.1.0
  test: ^1.31.2
  web: ^1.1.1

