/// Statistical computations and algorithms.
export 'src/stats/distribution.dart';
export 'src/stats/distributions/continuous.dart';
export 'src/stats/distributions/continuous/exponential.dart';
export 'src/stats/distributions/continuous/gamma.dart';
export 'src/stats/distributions/continuous/inverse_gamma.dart';
export 'src/stats/distributions/continuous/normal.dart';
export 'src/stats/distributions/continuous/student_t.dart';
export 'src/stats/distributions/continuous/uniform.dart';
export 'src/stats/distributions/continuous/weibull.dart';
export 'src/stats/distributions/discrete.dart';
export 'src/stats/distributions/discrete/bernoulli.dart';
export 'src/stats/distributions/discrete/binomial.dart';
export 'src/stats/distributions/discrete/negative_binomial.dart';
export 'src/stats/distributions/discrete/poisson.dart';
export 'src/stats/distributions/discrete/uniform.dart';
export 'src/stats/distributions/errors.dart';
export 'src/stats/iterable.dart';
export 'src/stats/jackknife.dart';
